### ISSUE TITLE
[DOC] Re-structure Data Prepper plugins documentation

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/documentation-website#1542]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
Data Prepper currently has a very large [Configuration reference](https://opensearch.org/docs/latest/clients/data-prepper/data-prepper-reference/) page. I'd like for us to break this up into multiple pages.

I propose that we have a single page per Data Prepper plugin/pipeline component. So for example, the `grok` processor would have its own page. The documentation for that page should include the configuration as well as information on what the plugin does and the metrics. You can get a sense of the documentation from the `grok` [README](https://github.com/opensearch-project/data-prepper/tree/main/data-prepper-plugins/grok-processor) file in the data-prepper repository (though please note that page includes details relevant for plugin authors which should not be on OpenSearch.org).

I also suggest that we group plugins by their role in the pipeline - `source`, `buffer`, `processor`, and `sink`.

So the structure may look like the following:

```
Clients and tools
  Data Prepper
    Get Started
    Pipelines
    Reference
      Data Prepper configuration
      Sources
        http
        otel_metrics_source
        otel_trace_source
        ...
      Buffers
        bounded_blocking
      Processors
        grok
        parse_json
        ...
      Sinks
        opensearch
        ...
```

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by graytaylor0** [comment]
I like this structure! Maybe we could have another section for the higher level pipeline configuration such as `workers` and `delay` as well

**Comment by dlvenable** [comment]
@graytaylor0 , perhaps the "Pipeline configuration" section as shown below?

```
Clients and tools
  Data Prepper
    ...
    Reference
      Data Prepper configuration
      Pipeline configuration
      Sources
        ...
      Buffers
        ...
      Processors
        ...
      Sinks
        ...
```

**Comment by cmanning09** [comment]
I like putting the metrics close to each plugin with this design. Metrics are missing in the public documentation. This change won't capture system or core data prepper metrics. Should we create a separate feature request?

**Comment by dlvenable** [comment]
> I like putting the metrics close to each plugin with this design. Metrics are missing in the public documentation. This change won't capture system or core data prepper metrics. 

I did suggest in the description that each plugin have:
1. Information about the plugin. This would be a textual description and may some usage examples.
2. Configuration information
3. Metrics information.

> Should I create a separate feature request or can we add a separate page in this reference section?

Let's include that in this proposal. I think another page under "Reference" makes sense here.

**Comment by graytaylor0** [comment]
@dlvenable Yes something like that makes sense. My only minor concern with the naming of `Pipeline configuration` would be that it clashes a bit with how we call the entirety of the `pipelines.yaml` a "pipeline configuration", but this may not be a problem

**Comment by dlvenable** [comment]
@graytaylor0 , I think that is a good point - there might be a better name here. Perhaps this page could discuss the basic concepts of pipelines at a high-level - sources, sinks, workers, etc. I'm not quite sure what to call it though.

**Comment by cmanning09** [comment]
> @graytaylor0 , I think that is a good point - there might be a better name here. Perhaps this page could discuss the basic concepts of pipelines at a high-level - sources, sinks, workers, etc. I'm not quite sure what to call it though.

This information is in an overview page In the repository: https://github.com/opensearch-project/data-prepper/blob/main/docs/overview.md . I am not sure if this helps. It may make sense to align on naming for these pages.

**Comment by sshivanii** [comment]
How about having a `Pipeline Configuration Structure` section similar to our Overview [sample config](https://github.com/opensearch-project/data-prepper/blob/main/docs/overview.md#sample-pipeline-configuration) which can have define the minimal components and have a General options section for `workers and delay`
```
##Pipeline Configuration Structure
Here's an example of a Basic pipeline configuration with minimal components. This configuration reads from file source and writes to a file source. It uses default options for other options for other components.

sample-pipeline:
  source:
    file:
        path: path/to/input-file
  sink:
    - file:
        path: path/to/output-file


###All components

sample-pipeline:
  workers: 4 #Number of workers
  delay: 100 # in milliseconds, how often the workers should run
  source:
    file:
        path: path/to/input-file
  buffer:
    bounded_blocking:
      buffer_size: 1024 # max number of records the buffer will accept
      batch_size: 256 # max number of records the buffer will drain for each read
  processor:
    - string_converter:
       upper_case: true
  sink:
    - file:
       path: path/to/output-file


```

Overall structure can look like:
```
Clients and tools
  Data Prepper
    ...
    Reference
      Pipeline Configuration Structure
      Sources
        ...
      Buffers
        ...
      Processors
        ...
      Sinks
        ...
```
