### ISSUE TITLE
[DOC] Docker images refer to an older version of dashboards

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/documentation-website#2234]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
The docker files on the docsite point to an older version of opensearch and opensearch-dashboards, version 1.0.1. We should instead change that to 

```yml
image: opensearchproject/opensearch:latest

and 

image: opensearchproject/opensearch-dashboards:latest
```

https://opensearch.org/docs/1.0/opensearch/install/docker#sample-docker-compose-file

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
