### ISSUE TITLE
[DOC] Feeback on /security/configuration/yaml/ page

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#3465]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 We received customer feedback on /docs/latest/security/configuration/yaml/ on 03/13/23:

"The documentation about role_mapping with openid and the openid documentation itselfs is ... not complete.. its not describe how opensearch-dashboards will receive the token from openid provider.. is it in the Authorization HTTP Header or opensearch pick it up by it self from the auth server (like in elasticsearch).. questions over questio..." 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
See https://opensearch.org/docs/latest/security/configuration/yaml/

**Comment by scrawfor99** [comment]
I can take this over :)

**Comment by scrawfor99** [comment]
Personally,  I feel the documentation covers an appropriate amount of information around OIDC. 

Looking for the specific info the comment mentions, I see:

```
```yml
openid_auth_domain:
  http_enabled: true
  transport_enabled: true
  order: 0
  http_authenticator:
    type: openid
    challenge: false
    config:
      subject_key: preferred_username
      roles_key: roles
      openid_connect_url: https://keycloak.example.com:8080/auth/realms/master/.well-known/openid-configuration
  authentication_backend:
    type: noop
```

The following table shows the configuration parameters.

Name | Description
:--- | :---
`openid_connect_url` | The URL of your IdP where the Security plugin can find the OpenID Connect metadata/configuration settings. This URL differs between IdPs. Required when using OpenID Connect as your backend.
`jwt_header` | The HTTP header that stores the token. Typically the `Authorization` header with the `Bearer` schema: `Authorization: Bearer <token>`. Optional. Default is `Authorization`.
`jwt_url_parameter` | If the token is not transmitted in the HTTP header, but as an URL parameter, define the name of the parameter here. Optional.
`subject_key` | The key in the JSON payload that stores the user's name. If not defined, the [subject](https://tools.ietf.org/html/rfc7519#section-4.1.2) registered claim is used. Most IdP providers use the `preferred_username` claim. Optional.
`roles_key` | The key in the JSON payload that stores the user's roles. The value of this key must be a comma-separated list of roles. Required only if you want to use roles in the JWT.


```

This notes that the info is usually passed in the header but you can also specify a URL parameter. This option will be use case dependent.
