### ISSUE TITLE
[BUG] DEV docker compose file is not running correctly

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/documentation-website#464]
Coming from here:
https://opensearch.org/docs/latest/opensearch/install/docker/#sample-docker-compose-file-for-development

This docker file trying to do single node deployment of OS and OSD but have errors after startup:
```
opensearch-node1         | org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: cannot start with [discovery.type] set to [single-node] when local node {opensearch-node1}{7Hv-pQgvTJe2mdoCpioU_g}{DM070OgbQUCn4x7F19VM-A}{172.18.0.2}{172.18.0.2:9300}{dimr}{shard_indexing_pressure_enabled=true} does not have quorum in voting configuration VotingConfiguration{IN9L2HDTRHGpIBU84xckEA}
opensearch-node1         | 	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.3.0.jar:1.3.0]
opensearch-node1         | 	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169) ~[opensearch-1.3.0.jar:1.3.0]
opensearch-node1         | 	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100) ~[opensearch-1.3.0.jar:1.3.0]
opensearch-node1         | 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-1.3.0.jar:1.3.0]
opensearch-node1         | 	at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-1.3.0.jar:1.3.0]
opensearch-node1         | 	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135) ~[opensearch-1.3.0.jar:1.3.0]
opensearch-node1         | 	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101) ~[opensearch-1.3.0.jar:1.3.0]
opensearch-node1         | Caused by: java.lang.IllegalStateException: cannot start with [discovery.type] set to [single-node] when local node {opensearch-node1}{7Hv-pQgvTJe2mdoCpioU_g}{DM070OgbQUCn4x7F19VM-A}{172.18.0.2}{172.18.0.2:9300}{dimr}{shard_indexing_pressure_enabled=true} does not have quorum in voting configuration VotingConfiguration{IN9L2HDTRHGpIBU84xckEA}
opensearch-node1         | 	at org.opensearch.cluster.coordination.Coordinator.doStart(Coordinator.java:843) ~[opensearch-1.3.0.jar:1.3.0]
opensearch-node1         | 	at org.opensearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:72) ~[opensearch-1.3.0.jar:1.3.0]
opensearch-node1         | 	at org.opensearch.node.Node.start(Node.java:1099) ~[opensearch-1.3.0.jar:1.3.0]
opensearch-node1         | 	at org.opensearch.bootstrap.Bootstrap.start(Bootstrap.java:339) ~[opensearch-1.3.0.jar:1.3.0]
opensearch-node1         | 	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:421) ~[opensearch-1.3.0.jar:1.3.0]
opensearch-node1         | 	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178) ~[opensearch-1.3.0.jar:1.3.0]
opensearch-node1         | 	... 6 more
opensearch-node1         | uncaught exception in thread [main]
opensearch-node1         | java.lang.IllegalStateException: cannot start with [discovery.type] set to [single-node] when local node {opensearch-node1}{7Hv-pQgvTJe2mdoCpioU_g}{DM070OgbQUCn4x7F19VM-A}{172.18.0.2}{172.18.0.2:9300}{dimr}{shard_indexing_pressure_enabled=true} does not have quorum in voting configuration VotingConfiguration{IN9L2HDTRHGpIBU84xckEA}
opensearch-node1         | 	at org.opensearch.cluster.coordination.Coordinator.doStart(Coordinator.java:843)
opensearch-node1         | 	at org.opensearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:72)
opensearch-node1         | 	at org.opensearch.node.Node.start(Node.java:1099)
opensearch-node1         | 	at org.opensearch.bootstrap.Bootstrap.start(Bootstrap.java:339)
opensearch-node1         | 	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:421)
opensearch-node1         | 	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178)
opensearch-node1         | 	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169)
opensearch-node1         | 	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
opensearch-node1         | 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
opensearch-node1         | 	at org.opensearch.cli.Command.main(Command.java:101)
opensearch-node1         | 	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135)
opensearch-node1         | 	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101)
opensearch-node1         | For complete error details, refer to the log at /usr/share/opensearch/logs/opensearch-cluster.log
```

Not completely the same error but seems like it hasnt run for a while:
https://github.com/opensearch-project/opensearch-build/issues/1775#issuecomment-1072103012

@Naarcha-AWS if you can take a look would be great.

Thanks.

**Comment by evs-xsarus** [comment]
*Below can be ignored*, turns out the docker fails when setting the _working_dir_. After removing it from my yaml, the docker did start.

Might be something to look into .

---
I've tried both YML's without success, they keep giving:

<pre>
ERROR: for opensearch13  Cannot start service opensearch13: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./opensearch-docker-entrypoint.sh": stat ./opensearch-docker-entrypoint.sh: no such file or directory: unknown

ERROR: for opensearch12  Cannot start service opensearch12: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./opensearch-docker-entrypoint.sh": stat ./opensearch-docker-entrypoint.sh: no such file or directory: unknown

ERROR: for opensearch13  Cannot start service opensearch13: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./opensearch-docker-entrypoint.sh": stat ./opensearch-docker-entrypoint.sh: no such file or directory: unknown
</pre>




I use this YAML:

```yaml
version: "3.7"
services:
  opensearch12:
    container_name: opensearch12
    image: opensearchproject/opensearch:1.2.4
    restart: always
    networks:
      - xsa_backend
    ports:
      - "9312:9200" # 93xx used to avoid conflicts with Elastic Search
      - "9612:9600" # required for Performance Analyzer
    working_dir: /sites
    environment:
      - cluster.name=opensearch12-cluster
      - node.name=opensearch12
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
      - "discovery.type=single-node" # disables bootstrap checks that are enabled when network.host is set to a non-loopback address
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536

  opensearch12-dashboards:
    container_name: opensearch12-dashboards
    image: opensearchproject/opensearch-dashboards:1.2.0
    restart: always
    networks:
      - xsa_backend
    ports:
      - 5612:5601
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch12:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" # disables security dashboards plugin in OpenSearch Dashboards
```

```yaml
version: "3.7"
services:
  opensearch13:
    container_name: opensearch13
    image: opensearchproject/opensearch:1.3.0
    restart: always
    networks:
      - xsa_backend
    ports:
      - "9313:9200" # 93xx used to avoid conflicts with Elastic Search
      - "9613:9600" # required for Performance Analyzer
    working_dir: /sites
    environment:
      - cluster.name=opensearch13-cluster
      - node.name=opensearch13
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
      - "discovery.type=single-node" # disables bootstrap checks that are enabled when network.host is set to a non-loopback address
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536

  opensearch13-dashboards:
    container_name: opensearch13-dashboards
    image: opensearchproject/opensearch-dashboards:1.3.0
    restart: always
    networks:
      - xsa_backend
    ports:
      - 5613:5601
    expose:
      - "5613"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch13:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" # disables security dashboards plugin in OpenSearch Dashboards
```

I'v tried it too while

* removing the 'DISABLE_SECURITY...' parts 
* adding volume mounts
