### ISSUE TITLE
[DOC] Clarify that there is no distinction between usernames from the internal database and external identity providers

### ISSUE THREAD

**Issue by davidlago** [opensearch-project/documentation-website#4937]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

We've seen cases where there is confusion with the way OpenSearch does/does not make a distinction between users based on where they are coming from. It does not. For example, user name `dave` represents the same user whether it is coming from the internal users database or an external LDAP. We should add a sentence in the [relevant documentation page](https://opensearch.org/docs/latest/security/authentication-backends/authc-index/) to signal as much.

**Comment by cwperks** [comment]
Consider these 2 roles mapping like this:

```
all_access:
  reserved: false
  backend_roles:
    - "admin"
  users:
    - "dave"
  description: "Maps admin backend role and dave user to all_access"

readall:
  reserved: false
  users:
  - "craig"
```

If I have 2 users called `dave` (one internal and one LDAP), they will both be mapped to `all_access` because of the user mapping.

Now let's say the internal user `craig` logs on. The internal user `craig` has no backend roles and is only mapped to `readall`.

Now an LDAP user named `craig` comes around and that LDAP user has a backend role admin
. When it comes to mapping the roles for that user they will get `readall` and `all_access`.

----- 

1. Direct user mappings in a roles_mapping would treat users from different IdPs as the same
2. Backend roles are unique to an IdP so if a user with the same username logs in through different IdPs, they may resolve to different sets of backend roles which could be mapped to different security roles.
