### ISSUE TITLE
[BUG] Security saml-example is using docker-compose file pointed to `1.0.1` 

### ISSUE THREAD

**Issue by peternied** [opensearch-project/documentation-website#618]
### What is the bug?
When demonstrating for users how to setup saml for their clusters an example docker compose file is offered to streamline configuration.  This file contains hardcoded references to the `1.0.1` release version of OpenSearch, which is not supported, instead this sample file should use the latest version(s) of OpenSearch/Dashboards.

### How can one reproduce the bug?
See https://github.com/opensearch-project/documentation-website/blob/main/assets/examples/saml-example.zip its hardcoded to a specific version and hasn't been updated since it was added.

### What is the expected behavior?
As newer versions of OpenSearch become available the sample file should be updated.  Note, a `latest` docker version identifier could be used.

Note; this file should also be stored as plaintext instead of a binary and dynamically assembled on website push - feel free to make another issue.

### Do you have any additional context?
From the `docker-compose.yml` file within that zip:
```
version: '3'
services:
  opensearch-saml-node1:
    image: opensearchproject/opensearch:1.0.1
    container_name: opensearch-saml-node1
    environment:
      - cluster.name=opensearch-saml-cluster
      - node.name=opensearch-saml-node1
      - discovery.seed_hosts=opensearch-saml-node1,opensearch-saml-node2
      - cluster.initial_master_nodes=opensearch-saml-node1,opensearch-saml-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
```
